package com.spark
 
import com.spark.Temperature
import java.io.File
import java.io.BufferedWriter

rule "Too Hot"
   dialect "mvel"
   when
      temp : Temperature( value > 85 )
   then
      System.out.println($temp.value.toString() + " F is too hot."+" Declare HEAT WARNING!"); 
end

rule "Too Cold"
   dialect "mvel"
   when
      temp : Temperature( value < 32 )
   then
      System.out.println($temp.value.toString() + " F is too cold." + " Declare FREEZE WARNING!"); 
end

rule "General"
   dialect "mvel"
   when
      temp : Temperature( value < 200 )
   then
      File file=new File("file.txt");
      BufferedWriter bf=new BufferedWriter(new PrintWriter(file));
      bf.append(temp.value.toString() + "Test Begin");
      System.out.println(temp.value.toString() + " Test Begin");
end
