package com.rules
 
import com.model.Temperature

rule "Too Hot"
   dialect "mvel"
   when
      temp : Temperature( value > 85 )
   then
      System.out.println(Double.toString(temp.value) + " F is too hot."+" Declare HEAT WARNING!");
      temp.setStatus(1);
end

rule "Too Cold"
   dialect "mvel"
   when
      temp : Temperature( value < 32 )
   then
      System.out.println(Double.toString(temp.value) + " F is too cold." + " Declare FREEZE WARNING!");
      temp.setStatus(-1);
end

