package com.test.rules
 
import com.test.model.weather.Temperature

rule "Too Hot"
   dialect "mvel"
   when
      temp : Temperature( value > 85 )
   then
      System.out.println(Double.toString(temp.value) + " F is too hot."+" Declare HEAT WARNING!");
end

rule "Too Cold"
   dialect "mvel"
   when
      temp : Temperature( value < 32 )
   then
      System.out.println(Double.toString(temp.value) + " F is too cold." + " Declare FREEZE WARNING!");
end

